In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

Matplotlib is building the font cache; this may take a moment.

In [2]:
BASE_DIR = os.path.dirname(os.getcwd())

file_path = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "hospital_cleaned.csv"
)

df = pd.read_csv(file_path)

df.head()

,Patient_ID,Hospital_ID,Department_Name,Admission_Date,Discharge_Date,Patient_Type,Readmission_Status,Outcome,Hospital_Name,Total_Beds,Occupied_Beds,Available_Medical_Equipment,Staff_Allocation_Count,Region,Length_of_Stay
0,P100001,H024,oncology,2025-01-06,2025-01-08,Day Care,No,Transferred,Manipal Hospital,57,33,78,96,South,2
1,P100002,H090,orthopedics,2025-05-26,2025-05-26,Day Care,Yes,Transferred,AIIMS Delhi,195,116,38,86,East,0
2,P100003,H043,dermatology,2026-01-19,2026-01-23,Emergency,No,Under Treatment,Max Super Speciality Hospital,164,92,13,61,North,4
3,P100004,H007,orthopedics,2025-04-20,2025-04-20,Day Care,Yes,Recovered,Aster CMI Hospital,188,152,15,111,West,0
4,P100005,H096,icu,2025-07-12,2025-07-16,Inpatient,Yes,Transferred,Christian Medical College Vellore,188,132,65,120,West,4

In [3]:
df.shape

(10000, 15)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Patient_ID                   10000 non-null  str
 1   Hospital_ID                  10000 non-null  str
 2   Department_Name              10000 non-null  str
 3   Admission_Date               10000 non-null  str
 4   Discharge_Date               10000 non-null  str
 5   Patient_Type                 10000 non-null  str
 6   Readmission_Status           10000 non-null  str
 7   Outcome                      10000 non-null  str
 8   Hospital_Name                10000 non-null  str
 9   Total_Beds                   10000 non-null  int64
 10  Occupied_Beds                10000 non-null  int64
 11  Available_Medical_Equipment  10000 non-null  int64
 12  Staff_Allocation_Count       10000 non-null  int64
 13  Region                       10000 non-null  str
 14  Length_of_Stay               10000 non-null  int64
dtypes: int64(5), str(10)
memory usage: 1.1 MB

In [5]:
df.describe()

,Total_Beds,Occupied_Beds,Available_Medical_Equipment,Staff_Allocation_Count,Length_of_Stay
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,121.563500,70.126600,45.360600,68.211500,4.991200
std,46.073865,39.288351,21.073362,29.250117,3.173725
min,40.000000,20.000000,10.000000,20.000000,0.000000
25%,80.000000,39.000000,26.000000,43.000000,2.000000
50%,123.000000,60.000000,45.000000,67.000000,5.000000
75%,162.000000,95.250000,64.000000,94.000000,8.000000
max,200.000000,193.000000,80.000000,120.000000,10.000000

In [6]:
df.isnull().sum()

Patient_ID                     0
Hospital_ID                    0
Department_Name                0
Admission_Date                 0
Discharge_Date                 0
Patient_Type                   0
Readmission_Status             0
Outcome                        0
Hospital_Name                  0
Total_Beds                     0
Occupied_Beds                  0
Available_Medical_Equipment    0
Staff_Allocation_Count         0
Region                         0
Length_of_Stay                 0
dtype: int64

In [7]:
dept_count = (
    df["Department_Name"]
    .value_counts()
)

dept_count

Department_Name
dermatology         1041
orthopedics         1032
neurology           1025
general medicine    1011
radiology            999
pediatrics           997
emergency            995
icu                  972
cardiology           971
oncology             957
Name: count, dtype: int64

In [8]:
hospital_admissions = (
    df["Hospital_Name"]
    .value_counts()
    .head(10)
)

hospital_admissions

Hospital_Name
Narayana Health                544
HCG Cancer Centre              539
Gleneagles Global Hospital     533
AIIMS Delhi                    531
KIMS Hospitals                 524
Yashoda Hospitals              523
Aster CMI Hospital             513
Care Hospitals                 506
Medanta                        503
Rainbow Children's Hospital    498
Name: count, dtype: int64

In [9]:
df["Length_of_Stay"].describe()

count    10000.000000
mean         4.991200
std          3.173725
min          0.000000
25%          2.000000
50%          5.000000
75%          8.000000
max         10.000000
Name: Length_of_Stay, dtype: float64

In [10]:
outcome = df["Outcome"].value_counts()

outcome

Outcome
Recovered          3380
Transferred        3322
Under Treatment    3298
Name: count, dtype: int64

In [11]:
df["Bed_Occupancy_Rate"] = (
    df["Occupied_Beds"] /
    df["Total_Beds"]
) * 100

In [12]:
region_data = df["Region"].value_counts()

region_data

Region
West     2833
East     2455
North    2427
South    2285
Name: count, dtype: int64